### PR TITLE
Adding support for rgba8 images

### PR DESCRIPTION
**Pull request by mikeparisstuff**
I'm new to this project and PDF internals in general but I was able to get RGBA8 images working. I've added an example that demonstrates the behavior with a transparent png of a cute pup. Let me know if you would like to see any changes but I think a number of people would benefit from this :)

### CODE REVIEW

**Review by fschutt — CHANGES_REQUESTED** [review]
`rgb.extend_from_slice(data[i..i + 2]);`

**Comment by fschutt** [comment]
Otherwise LGTM am on mobile rn, will review later

**Comment by AxelNilsson** [comment]
Great PR! However, this only works for square images, will see if I can do a fix.

**Comment by huand** [comment]
pinging @mikeparisstuff there are maybe issues that you might have better understanding? https://github.com/fschutt/printpdf/issues/166

thanks if you have time to take a look!

**Pull request merged**
