### PR TITLE
removed the dependency on stdweb - resolves #144

### LINKED ISSUE #144: target wasm32 is using stdweb
I am not sure which package tring to install stdweb but lopdf and printpdf using time package and somehow it install stdweb 0.4.2 which it is not compatible with syn v2. It only depends on wasm32 target.

### PR DESCRIPTION
**Pull request by LiamPClancy**
upgraded lopdf to v 0.31.0, and upg…raded time dependency to 0.3.25, the upgrade to lopdf required a significant number of the f64 values to be changes to f32 to remain compatible.

### CODE REVIEW

**Comment by LiamPClancy** [comment]
fixed the test that was failing, the test has demonstrated that the conversion to f32 was only accurate to the f64 to 6 decimal places, i've just modified the test to take the results from the f32 calculations

**Comment by LiamPClancy** [comment]
So I appoligise for the initial failures, I was only running the tests against the targets I had set, 
noticed that the pipelines failed, so ran against all targets - got a few issues, 
I basically had to change all the f64 to f32 across the crate, 
after completing the tests all pass now for all targets.

**Comment by fschutt** [comment]
@learnplaycreate there are still failing tests, can you rebase onto master + fix the precision issue in the failing test? Thanks.

**Comment by eribol** [comment]
Thank you, i already make it work on my local but did not trust my capable of for PR :)

**Comment by LiamPClancy** [comment]
@fschutt happy to fix tests that are failing, but when I run 
`cargo test --all-targets --all-features`
i'm getting all test passing. 
let me know what I should be running to see the failed tests?

**Comment by fschutt** [comment]
@learnplaycreate I know what the issue is, I'll fix it. LGTM otherwise.

**Pull request merged**
